### ISSUE TITLE
Take it further?

### ISSUE THREAD

**Issue by shelldandy** [estrattonbailey/nanoclass#1]
```js
export default c => c.filter(Boolean).join(' ')
```

**Comment by shelldandy** [comment]
47bytes letsgooo

**Comment by estrattonbailey** [comment]
@shelldandy lol just saw this. Yeah idk I was on a non-arrow function kick for a while there. I'm gonna do this right now just bc why not haha.

**Comment by estrattonbailey** [comment]
😎 
```
export default c=>c.filter(c=>!!c).join(' ')
```

Ya know the funny thing is that Bublé still converts to `function` decls so it's still `80b` ¯\_(ツ)_/¯

**Comment by shelldandy** [comment]
:((((((((((((((((((((((
